config/routes.rb
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  # Root
  root to: "main#index"

  # sign-in 
  get "/sign_in", to: "sessions#new"
  post "/sign_in", to: "sessions#create"

  # sign-out 
  delete "/sign_out", to: "sessions#destroy"
  
  # category routes
  post '/category/add', to: 'category#create'                                             
  get  '/category/:category_id', to: "category#fetch_category"                             
  get  '/categories', to: "category#fetch_all"                                              

  # Item routes
  get '/item/:item_id', to: "item#show_item", as: "show_item"     
  post "/item", to: "item#create"                                                             
  get '/item/category/:category_id', to: "item#show_category_items", as: 'category_items'     
  get '/search/item', to: "item#search"
  get '/view_cart', to: "item#fetch_by_carts", as: "fetch_cart"                                
  post 'item/cart', to: "item#add_item_to_cart"                                                

  post 'audio/upload', to: "audio#upload_audio"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :customer
    has_many :items_by_carts, dependent: :destroy
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :items, dependent: :destroy
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
    validates :first_name, presence: true # Validate first_name field
    validates :last_name, presence: true  # validate last_name field
    validates :email, presence: true    # validate email field
    has_one :cart 
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :category
    has_many :items_by_carts
end

app/models/items_by_cart.rb
class ItemsByCart < ApplicationRecord
    belongs_to :item
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user

    def set_current_user
        if session[:customer_id]
            Current.customer = Customer.find_by(id: session[:customer_id])
        end
    end
end

app/controllers/audio_controller.rb
require "google/cloud/storage"

class AudioController < ApplicationController
    skip_before_action :verify_authenticity_token

    # Action to upload audio to GCS and translate. Calls the SpeechTextConverter Service
    def upload_audio 
        # Get the uploaded file from the params 
        audio_file = params[:audio_file]

        words = SpeechTextConverter.call(audio_file)
        
        # select only words that are nouns
        noun_terms = words.select{ |key, value| value == :NOUN}
        key = noun_terms.keys[0]

        # Show all products if there is no text identified
        if key == nil 
           return redirect_to search_item_path(key: "")  
        end
        
        redirect_to search_item_path(key: key)
        return 
    end
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  skip_before_action :verify_authenticity_token
  # action to add new category
  def create
    # save all categories to the db
    @categories = Category.create(category_params)
  end

  private 
  def category_params
    params.permit(category: [
      :category_name, 
      :slug, 
      :description, 
      :img_src ]).require(:category)
  end
end

app/controllers/item_controller.rb
class ItemController < ApplicationController
  skip_before_action :verify_authenticity_token

  # Action to create a new item
  def create
    for item in item_params
      category_slug = item[:category]
      @category = Category.find_by(slug: category_slug)
      item.delete(:category)
      @category.items.create(item)
    end
  end


  # Action to show items in a category
  def show_category_items
    category_id = params[:category_id]
    @category = Category.find(category_id)
    @items = @category.items.all

    render "items_category"
  end

  # Action to show one item
  def show_item 
    item_id = params[:item_id]
    @item = Item.find(item_id)

    render "show_item"
  end

  # Action to fetch items in a cart
  def fetch_by_carts
    @cart = Current.customer.cart
    cart_items = @cart.items_by_carts 
    items_id = cart_items.map { |product| product.item_id }
    
    distinct_items_id = Set.new(items_id).to_a
    @items = Item.where(id: distinct_items_id)

  end 

  # Action to add item to cart
  def add_item_to_cart
    item_id = params[:item_id]
    item = Item.find(item_id)
    customer_id = Current.customer.id
    cart = Current.customer.cart
    quantity = 1
    cart.items_by_carts.create(
      item_id: item_id,
      quantity: quantity,
    )

    total = cart.sub_total.to_f + item.price.to_f

    cart.update(
      sub_total: total
    )

  end

  # Action to search for an item
  def search 
    @key = params[:key].downcase()
    key = "%#{@key}%"
    @items = Item.where("LOWER(item_name)LIKE ?", key)

    render "search"
  end

  private
  def item_params
    params.permit(item: [
      :item_name, 
      :stock_number, 
      :description, 
      :price, 
      :image_src,
      :category]).require(:item)
  end

  def cart_item 
    params.permit(item: [
      :item_id ,
      :quantity
    ]).require(:item)
  end
end

app/controllers/main_controller.rb
class MainController <ApplicationController
    # Fetch all categories and render the index view
    def index
        @categories = Category.all
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    # Sign in page
    def new 

    end

    # Create new customer or fetch existing customer
    def create
        existing_customer = Customer.where(
            first_name: params[:first_name],
            last_name: params[:last_name],
            email: params[:email]).first
        
        if existing_customer
            session[:customer_id] = existing_customer.id
            redirect_to root_path
        else  
            @customer = Customer.new(customer_params)
            customer = @customer.save 
            session[:customer_id] = @customer.id 
            @customer.build_cart()
            @customer.cart.save
            redirect_to root_path
        end
    end

    # sign out
    def destroy 
        session[:customer_id] = nil
        redirect_to sign_in_path, notice: "Logged out"
    end

    private 
    def customer_params
        params.permit(:first_name, :last_name, :email)
    end
    

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/audio_helper.rb
module AudioHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/views/item/fetch_by_carts.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag 'show_carts' %>
<% end %>

<div class="main-cart-container">
    <div class="column-1">
        <div class="header">
            <h2> My Cart</h2>
        </div>
        <% @items.each do |item| %>
            <div class="cart-items">
                <div class="image-wrapper">
                    <%= image_tag item.image_src, class:"item-image" %>
                </div>
                <div class="content">
                    <p class="price">$<%= item.price %></p>
                    <p class="name"><%= item.item_name %></p>
                </div>
            </div>
        <% end %>
        <div class="sub-total">
            <p>Sub-total </p>
            <span>$<%= @cart.sub_total %></span>
        </div>
    </div>
    <div class="column-2">
        <div class="header">
            <h2>Total</h2>
        </div>
        <hr>
        <div class="checkout-description">
            <div class="description">
                <p>Sub-total</p>
                <span>$<%= @cart.sub_total %></span>
            </div>
            <div class="description">
                <p>Delivery</p>
            </div>
        </div>
        <hr>
        <div class="checkout">
            <p>Checkout</p>
        </div>
        <div class="payments">
            <p>We Accept:</p>
            <div class="payment-images">

            </div>
        </div>
    </div>
</div>

app/views/item/items_category.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag 'items_category' %>
<% end %>

<div class="main-container">
		<h3 class="category-header"><%= @category.category_name %></h3>
    <div class="item-container">
			<% @items.each do |item| %>
				<div class="single-item-container">
					<%= link_to show_item_path(:item_id => item.id) do %>
						<div class="image-wrapper">
								<%= image_tag item.image_src, class:"item-image" %>
						</div>
						<p class="item-name"><%= item.item_name %></p>
						<p class="item-price">$<%= item.price %></p>
					<% end %>
				</div>
			<% end %>
    </div>
</div>

app/views/item/search.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag 'search' %>
<% end %>
<span id="my-element" data-key="shoe"></span>
<div class="search-main-container">
	<h3>Your search results for: 
		<br/> 
		<span class="search-key">"<%= @key %>"</span>
	</h3>
	<div class="products-container">
		<% @items.each do |item| %>
			<%= link_to show_item_path(:item_id => item.id) do %>
				<div class="product-container">
					<div class="product-image-container">
						<%= image_tag item.image_src, class:"product-image" %>
					</div>
					<div class="product-description">
						<p class="name"><%= item.item_name %></p>
						<p class="description"><%= item.description %></p>
						<p class="price">$<%= item.price %></p>
					</div>
				</div>
			<% end %>
		<% end %>
	</div>
</div>

app/views/item/show_item.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag 'show_item' %>
<% end %>

<div class="item-main-container">
	<div class="image-container">
		<%= image_tag @item.image_src, class:"item-image" %>
	</div>
	<div class="description-container">
		<h3 class="item-name"><%= @item.item_name %>
		<p class="item-price">$<%= @item.price %></p>
		<div class="cart-container" id="add-button" data-id="<%= params[:item_id] %>">
			<div>
				<h2>Add to cart</h2>
			</div>
		</div>
	</div>
</div>

<%= javascript_pack_tag 'show', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ECommerceSite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <%= yield(:head) %>
  
    <%= stylesheet_link_tag 'navbar', media: 'all', 'data-turbolinks-track': 'reload' %> 
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% unless params[:action] == 'new' %>
      <%= render partial: "shared/navbar" %>
    <% end %>

    <div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag 'index' %>
<% end %>

<div class="main-container">
  <div class="Header">
		<h3>Categories</h3>
	</div>
	<div class="categories-container">
		<% @categories.each do |category| %>
			<div class="single-category-container">
				<%= link_to category_items_path(:category_id => category.id) do %>
					<div class="image-container">
						<%= image_tag category.img_src.to_s, class: "category-image" %>
					</div>
					<h3>
						<span class="category-name"><%= category.category_name %></span>
					</h3>
				<% end %>
			</div>
		<% end %>
	</div>
</div>

app/views/shared/_navbar.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag 'navbar' %>
<% end %>

<div class="top-container">
  <div class="top-banner">
    <%= image_tag "mic.jpeg", class: "mic-image" %>
    <p class="banner-text"> Voice Shop has officially launched as a voice empowered e-commerce site. <a href="#">Learn more</a></p>
  </div>
</div>
<nav class="navbar navbar-expand-lg">
  <div class="container-fluid sub-banner bg-body-tertiary">
    <div class="collapse navbar-collapse nav-overall-container">
      <div>
        <ul class="navbar-nav nav-first-section">
          <li class="nav-item">
            <%= link_to "Home", root_path, class:"nav-link active" %>
          </li>
        </ul>
      </div>

      <div class="search-bar">
        <form id="search-products" action='/search/item'>
          <input class="search" name="key" type="text" placeholder="Search products"/>
        </form>
        <%= image_tag "voice.png", class: "voice-image", id: "record-button" %>
      </div>

      <div class="right-container">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0 right-nav-container">
          <% if Current.customer %>
            <li class="nav-item name-container">
              <span class="name right-nav-item"><%= "Hi, #{Current.customer.first_name}"%></span>
            </li>
            <li class="nav-item cart-container">
              <%= image_tag "cart.png", class: "cart-image" %>
              <%= link_to "Cart", fetch_cart_path, class: "nav-link right-nav-item" %>
            </li>
            <li class="nav-item">
              <%= link_to "Logout", sign_out_path, method: :delete, class: "right-nav-item" %>
            </li class="nav-item">
          <% else %>
            <li class="nav-item login">
              <%= link_to "Login", sign_in_path, class: "nav-link right-nav-item" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>

<audio id="blip-in">
  <source src="<%= asset_path('blip_in.mp3') %>" type="audio/mpeg">
</audio>
<audio id="blip-out">
  <source src="<%= asset_path('blip_out.mp3') %>" type="audio/mpeg">
</audio>

<%= javascript_pack_tag 'navbar' %>